In [4]:
#計算矩阵的特征值與特征向量
import numpy as np
A=np.matrix('1,3;2,5')
A

matrix([[ 0.1513182 , -3.09626531],
        [-0.05862459, -5.32792709]])

In [5]:
ev,P=np.linalg.eig(A)
ev

array([-0.16227766,  6.16227766])

In [6]:
P

matrix([[-0.93246475, -0.50245469],
        [ 0.36126098, -0.86460354]])

In [7]:
D=np.diag(ev)
D

array([[-0.16227766,  0.        ],
       [ 0.        ,  6.16227766]])

In [12]:
print(np.dot(P,D))
print(np.dot(A,P))
#兩個结果相等

[[ 0.1513182  -3.09626531]
 [-0.05862459 -5.32792709]]
[[ 0.1513182  -3.09626531]
 [-0.05862459 -5.32792709]]


In [18]:
#最小平方法線性回歸
x=np.array([1,2,4,3,2,3,4,1,5])
y=np.array([1.4,4.2,10.4,5.8,4.8,6.7,8.5,3.1,9.2])
print(x)
print(y)

[1 2 4 3 2 3 4 1 5]
[ 1.4  4.2 10.4  5.8  4.8  6.7  8.5  3.1  9.2]


In [14]:
X=np.vstack((np.ones(9),x)).T
X

array([[1., 1.],
       [1., 2.],
       [1., 4.],
       [1., 3.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 1.],
       [1., 5.]])

In [20]:
beta,SSR,rank,sv=np.linalg.lstsq(X,y)
beta

/Users/wenruiling/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


array([0.41785714, 2.01357143])

In [33]:
print(f"SSR is{SSR} ")
print(f"Rank is {rank}")
print(f"Sv is{sv}")

SSR is[7.55935714] 
Rank is 2
Sv is[9.61697778 1.23034074]


In [34]:
B=np.dot(X.T,X)
B

array([[ 9., 25.],
       [25., 85.]])

In [35]:
Bi=np.linalg.inv(B)
Bi

array([[ 0.60714286, -0.17857143],
       [-0.17857143,  0.06428571]])

In [36]:
C=np.dot(Bi,X.T)
C

array([[ 0.42857143,  0.25      , -0.10714286,  0.07142857,  0.25      ,
         0.07142857, -0.10714286,  0.42857143, -0.28571429],
       [-0.11428571, -0.05      ,  0.07857143,  0.01428571, -0.05      ,
         0.01428571,  0.07857143, -0.11428571,  0.14285714]])

In [37]:
beta2=np.dot(C,y)
beta2

array([0.41785714, 2.01357143])

In [38]:
beta#看到beta等於beta2

array([0.41785714, 2.01357143])